version: '3'

services:
  api:
    container_name: mydocker-api
    image: mydocker/api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.production
    environment:
      - VIRTUAL_HOST=api.domain.com
      - VIRTUAL_PORT=3000 # Keep VIRTUAL_PORT to 3000. Dont Change!
      - LETSENCRYPT_HOST=api.domain.com
      - LETSCRYPT_EMAIL=webmaster@domain.com
      - HTTPS_METHOD=redirect
    expose:
      - 80
    env_file:
      - .env.production

networks:
  default:
    external:
      name: nginx-proxy
