FROM node:16-alpine

ENV SRCDIR /src

# Add custom environment to pass in production server
ENV PATH $SRCDIR/app/node_modules/.bin:$PATH
RUN mkdir -p $SRCDIR/app && chown -R node:node $SRCDIR

WORKDIR $SRCDIR/app

COPY package.json .
RUN yarn --verbose
RUN yarn global add serve

COPY . .
RUN yarn build

# Keep Port for production to 3000. Dont Change!
EXPOSE 3000

CMD serve -s build