version: '3.9'

services:
  api:
    container_name: mydocker-api-local
    image: mydocker/api-local
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - '3001:3001'
    volumes:
      - .:/src/app
      - /src/app/node_modules
    env_file:
      - .env.local
