FROM node:16-alpine

ENV SRCDIR /src

# Add custom environment to pass in local development
ENV PATH $SRCDIR/app/node_modules/.bin:$PATH
RUN mkdir -p $SRCDIR/app && chown -R node:node $SRCDIR

WORKDIR $SRCDIR/app

COPY package.json .

RUN yarn --verbose

COPY . .

EXPOSE 3001

CMD ["yarn", "start"]